//
// Created by Samuel Jones on 1/9/22.
//

#ifndef EPAPER_DISPLAY_CRYPTOGRAPHY_H
#define EPAPER_DISPLAY_CRYPTOGRAPHY_H

void CRYPTOGRAPHY_Init(void);
void CRYPTOGRAPHY_RSA_Generate();

#endif //EPAPER_DISPLAY_CRYPTOGRAPHY_H
