
[application]
name = "message_box"

[[resource]]
name = "messages"
url = "127.0.0.1:8000/dev_api/message_box/6/responses"
local_name = "message_box.toml"
auth = true

#[[resource]]
#name = "symbols"
#url = "127.0.0.1:8000/dev_api/symbols"
#local_name = "symbols.toml"
#auth = true

[render_root]
	[[render_root.symbol]]
		x = 50
		y = 50
		max_width = 50
		max_height = 50
		right = true
		bottom = true
		id = 0
	[[render_root.symbol]]
		x = 50
		y = 50
		max_width = 50
		max_height= 50
		right=true
		id = 1
	[[render_root.symbol]]
		x = 50
		y = 50
		max_width = 50
		max_height = 50
		vertical_center = true
		horizontal_center = true
		id = 2
	[[render_root.symbol]]
		x = 50
		y = 50
		max_width = 50
		max_height = 50
		bottom = true
		id = 3
	[[render_root.text]]
		y = 100
		width = 800
		height = 250
		vertical_center = true
		horizontal_center = true
		value = "abcdefghijklmnopqrstuvwxyz\nABCDEFGHIJKLMNOPQRSTUVWXYZ\n1234567890\n!#$%?.,_-+=/\\()[]{}|\"'"
		font = "BITTER_PRO_48"
	[[render_root.box]] # small region on the right of the screen
		x = 600
		y = 0
		width = 200
		height = 480
		[[render_root.box.text]]
			y = 100
			width = 200
			height = 250
			vertical_center = true
			horizontal_center = true
			value = "Brandon\n&\nKenzie"
			font = "BITTER_PRO_48"
		[[render_root.box.text]]
			y = 250
			width = 200
			height = 100
			vertical_center = true
			horizontal_center = true
			value = "02 . 05 . 2022"
			font = "BITTER_PRO_24"
		[[render_root.box.text]]
			y = 250
			width = 200
			height = 100
			vertical_center = true
			horizontal_center = true
			value = "leave a message!"
			font = "BITTER_PRO_24"
		[[render_root.box.image]]
			y = 250
			width = 200
			height = 100
			vertical_center = true
			horizontal_center = true
			value = "!!BROB_KENZ_QR_CODE!!"
		[[render_root.box.text]]
			y = 350
			width = 200
			height = 100
			bottom = true
			horizontal_center = true
			value = "hambones.app/\nthisisnotapuzzle"
			font = "BITTER_PRO_24"

	[[render_root.box]] # big region on the left of the screen
		x = 0
		y = 0
		width = 600
		height = 480
		[[render_root.box.text]]
			x = 0
			y = 0
			width = 200
			height = 480
			vertical_center = true
			horizontal_center = true
			value = "!!MSG_BOX_AUTHOR!!"
			font = "BITTER_PRO_24"
		[[render_root.box.text]]
			x = 200
			y = 0
			width = 200
			height = 100
			vertical_center = true
			horizontal_center = true
			value = "!!MSG_BOX_MESSAGE!!"
			font = "BITTER_PRO_24"
		# Add: separator between author and text

		# To do: more decorative stuff?

	[[render_root.box]] # Vertical Divider between the two regions
		x = 590
		y = 0
		width = 20
		height = 480
		# To do: render? with rectangles

