[[message]]
author = "ham"
message_text = "A test short message."

[[message]]
author = "Sam Jones"
message_text = "Generic well wishes! We're/I'm so happy for you! Wishing you lots of love and happiness. Wishing you a long and happy marriage. Wishing you the best today and always. So happy to celebrate this day with you both! Best wishes for a fun-filled future together. Wishing you fulfillment of every dream!"

